alias copy='xsel -ib'
alias paste='xsel -ob'
alias timestamp='date +%s'
alias boltbrowser='$GOPATH/bin/boltbrowser'
alias cds='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
